-- Run this in Hostinger phpMyAdmin (database: u278432002_tool)

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(50) PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  mobile VARCHAR(20) NOT NULL DEFAULT '',
  password_hash VARCHAR(255) NOT NULL,
  user_token VARCHAR(128) NULL UNIQUE,
  name VARCHAR(255) NOT NULL DEFAULT '',
  user_type VARCHAR(20) NOT NULL DEFAULT 'staff',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  token VARCHAR(128) PRIMARY KEY,
  user_id VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_sessions_user (user_id)
);

CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  mobile VARCHAR(20) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  pin VARCHAR(20) NOT NULL DEFAULT '',
  pan VARCHAR(10) NULL UNIQUE,
  businesses JSON NOT NULL,
  fy_closed_overrides JSON NOT NULL,
  fy_statement_type_overrides JSON NOT NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS businesses (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  type VARCHAR(100) NOT NULL DEFAULT '',
  pan VARCHAR(10) NOT NULL,
  address TEXT NOT NULL,
  starting_fy VARCHAR(20) NOT NULL DEFAULT '',
  starting_year INT NOT NULL,
  gst_number VARCHAR(20) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMP NULL,
  deleted_by_user_id VARCHAR(50) NULL,
  deleted_by_username VARCHAR(100) NULL,
  deleted_by_name VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  INDEX idx_businesses_client (client_id),
  INDEX idx_businesses_status (status)
);

CREATE TABLE IF NOT EXISTS fs_data (
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  payload JSON NOT NULL,
  PRIMARY KEY (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS financial_years (
  id VARCHAR(50) PRIMARY KEY,
  label VARCHAR(20) NOT NULL DEFAULT '',
  start_year INT NOT NULL,
  end_year INT NOT NULL,
  statement_type VARCHAR(50) NOT NULL DEFAULT 'Actual',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMP NULL,
  deleted_by_user_id VARCHAR(50) NULL,
  deleted_by_username VARCHAR(100) NULL,
  deleted_by_name VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  INDEX idx_financial_years_deleted (is_deleted),
  INDEX idx_financial_years_start_year (start_year)
);

CREATE TABLE IF NOT EXISTS ca_profiles (
  id VARCHAR(50) PRIMARY KEY,
  firm_name VARCHAR(255) NOT NULL DEFAULT '',
  partner_name VARCHAR(255) NOT NULL DEFAULT '',
  firm_type VARCHAR(100) NOT NULL DEFAULT '',
  frn_number VARCHAR(100) NOT NULL DEFAULT '',
  membership_number VARCHAR(100) NOT NULL DEFAULT '',
  udin VARCHAR(100) NOT NULL DEFAULT '',
  seal_signature_name VARCHAR(255) NOT NULL DEFAULT '',
  seal_signature_data_url LONGTEXT NULL,
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL DEFAULT '',
  pin VARCHAR(20) NOT NULL DEFAULT '',
  place VARCHAR(100) NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMP NULL,
  deleted_by_user_id VARCHAR(50) NULL,
  deleted_by_username VARCHAR(100) NULL,
  deleted_by_name VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  INDEX idx_ca_profiles_deleted (is_deleted)
);

CREATE TABLE IF NOT EXISTS ledgers (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  note_group VARCHAR(100) NOT NULL DEFAULT 'otherAdministrativeExpenses',
  sign VARCHAR(10) NOT NULL DEFAULT 'add',
  sort_order INT NOT NULL DEFAULT 0,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMP NULL,
  deleted_by_user_id VARCHAR(50) NULL,
  deleted_by_username VARCHAR(100) NULL,
  deleted_by_name VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  INDEX idx_ledgers_deleted (is_deleted),
  INDEX idx_ledgers_group (note_group)
);

CREATE TABLE IF NOT EXISTS udin_records (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  ca_profile_id VARCHAR(50) NOT NULL DEFAULT '',
  ca_partner_name VARCHAR(255) NOT NULL DEFAULT '',
  ca_firm_name VARCHAR(255) NOT NULL DEFAULT '',
  udin_number VARCHAR(100) NOT NULL DEFAULT '',
  issue_date DATE NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  seal_attachment_name VARCHAR(255) NOT NULL DEFAULT '',
  seal_attachment_data_url LONGTEXT NULL,
  seal_offset_x DECIMAL(5,2) NOT NULL DEFAULT 82,
  seal_offset_y DECIMAL(5,2) NOT NULL DEFAULT 50,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_udin_fs (client_id, fy_id, business_id),
  INDEX idx_udin_ca (ca_profile_id),
  INDEX idx_udin_client_fy (client_id, fy_id)
);

CREATE TABLE IF NOT EXISTS depreciation_schedule_rows (
  id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  ledger_id VARCHAR(50) NULL,
  asset_name VARCHAR(255) NOT NULL DEFAULT '',
  purchase_date DATE NULL,
  rate DECIMAL(8, 2) NOT NULL DEFAULT 0,
  opening_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_before_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_on_after_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  asset_deletion DECIMAL(18, 2) NOT NULL DEFAULT 0,
  depreciation DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (client_id, fy_id, business_id, id),
  INDEX idx_dep_schedule_fs (client_id, fy_id, business_id),
  INDEX idx_dep_schedule_ledger (ledger_id)
);

CREATE TABLE IF NOT EXISTS depreciation_previous_year (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  opening_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_before_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_on_after_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  asset_deletion DECIMAL(18, 2) NOT NULL DEFAULT 0,
  depreciation DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_dep_prev_fs (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS asset_depreciation_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  ledger_id VARCHAR(50) NULL,
  asset_name VARCHAR(255) NOT NULL DEFAULT '',
  purchase_date DATE NULL,
  rate DECIMAL(8, 2) NOT NULL DEFAULT 0,
  opening_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_before_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  addition_on_after_oct3 DECIMAL(18, 2) NOT NULL DEFAULT 0,
  asset_deletion DECIMAL(18, 2) NOT NULL DEFAULT 0,
  depreciation_charged DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_wdv DECIMAL(18, 2) NOT NULL DEFAULT 0,
  schedule_row_id VARCHAR(50) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_asset_dep_history (client_id, business_id, fy_id, ledger_id),
  INDEX idx_asset_dep_history_lookup (client_id, business_id, ledger_id),
  INDEX idx_asset_dep_history_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS bank_account_rows (
  id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  bank_name VARCHAR(255) NOT NULL DEFAULT '',
  account_number VARCHAR(100) NOT NULL DEFAULT '',
  account_type VARCHAR(20) NOT NULL DEFAULT 'current',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  closed_in_fy_id VARCHAR(50) NULL,
  opening_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  debit DECIMAL(18, 2) NOT NULL DEFAULT 0,
  credit DECIMAL(18, 2) NOT NULL DEFAULT 0,
  bank_charge DECIMAL(18, 2) NOT NULL DEFAULT 0,
  interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (client_id, fy_id, business_id, id),
  INDEX idx_bank_accounts_fs (client_id, fy_id, business_id),
  INDEX idx_bank_accounts_lookup (client_id, business_id, account_number)
);

CREATE TABLE IF NOT EXISTS bank_account_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  bank_account_id VARCHAR(50) NOT NULL,
  bank_name VARCHAR(255) NOT NULL DEFAULT '',
  account_number VARCHAR(100) NOT NULL DEFAULT '',
  account_type VARCHAR(20) NOT NULL DEFAULT 'current',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  closed_in_fy_id VARCHAR(50) NULL,
  opening_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  debit DECIMAL(18, 2) NOT NULL DEFAULT 0,
  credit DECIMAL(18, 2) NOT NULL DEFAULT 0,
  bank_charge DECIMAL(18, 2) NOT NULL DEFAULT 0,
  interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_bank_account_history (client_id, business_id, fy_id, bank_account_id),
  INDEX idx_bank_account_history_year (client_id, business_id, fy_start_year),
  INDEX idx_bank_account_history_account (client_id, business_id, bank_account_id)
);

CREATE TABLE IF NOT EXISTS gst_reco_records (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  link_sales_to_revenue_note TINYINT(1) NOT NULL DEFAULT 0,
  link_closing_to_notes TINYINT(1) NOT NULL DEFAULT 0,
  closing_from_notes_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_from_notes_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_from_notes_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sales_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sales_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sales_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sales_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  amended_sales DECIMAL(18, 2) NOT NULL DEFAULT 0,
  amended_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  amended_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  amended_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_igst_to_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_igst_to_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_igst_to_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_cgst_to_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_cgst_to_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_sgst_to_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_sgst_to_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_cash_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_cash_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ot_cash_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_3b_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_3b_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_3b_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_prev_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_prev_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_prev_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_2b_igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_2b_cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sr_2b_sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_gst_reco_fs (client_id, fy_id, business_id),
  INDEX idx_gst_reco_client_fy (client_id, fy_id)
);

CREATE TABLE IF NOT EXISTS gst_reco_input_tax_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  row_type VARCHAR(50) NOT NULL,
  particular VARCHAR(500) NOT NULL DEFAULT '',
  igst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  cgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sgst DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_gst_reco_input_row (client_id, fy_id, business_id, row_type),
  INDEX idx_gst_reco_input_fs (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS gst_reco_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_gst_reco_history (client_id, business_id, fy_id),
  INDEX idx_gst_reco_history_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS loan_records (
  id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  lender VARCHAR(255) NOT NULL DEFAULT '',
  loan_type VARCHAR(20) NOT NULL DEFAULT 'long-term',
  opening_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  disbursement DECIMAL(18, 2) NOT NULL DEFAULT 0,
  disbursement_date DATE NULL,
  interest_rate DECIMAL(8, 4) NOT NULL DEFAULT 0,
  tenure_months INT NOT NULL DEFAULT 0,
  emi_start_date DATE NULL,
  prepayment_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  prepayment_date DATE NULL,
  is_closed TINYINT(1) NOT NULL DEFAULT 0,
  closing_adj_enabled TINYINT(1) NOT NULL DEFAULT 0,
  closing_adj_mode VARCHAR(32) NOT NULL DEFAULT 'principal-interest',
  closing_adj_principal DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_target_balance DECIMAL(18, 2) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (client_id, fy_id, business_id, id),
  INDEX idx_loan_records_fs (client_id, fy_id, business_id),
  INDEX idx_loan_records_lookup (client_id, business_id, lender)
);

CREATE TABLE IF NOT EXISTS loan_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  loan_id VARCHAR(50) NOT NULL,
  lender VARCHAR(255) NOT NULL DEFAULT '',
  loan_type VARCHAR(20) NOT NULL DEFAULT 'long-term',
  opening_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  disbursement DECIMAL(18, 2) NOT NULL DEFAULT 0,
  disbursement_date DATE NULL,
  interest_rate DECIMAL(8, 4) NOT NULL DEFAULT 0,
  tenure_months INT NOT NULL DEFAULT 0,
  emi_start_date DATE NULL,
  prepayment_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  prepayment_date DATE NULL,
  emi_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  interest_for_year DECIMAL(18, 2) NOT NULL DEFAULT 0,
  principal_repaid DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  schedule_closing_balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_enabled TINYINT(1) NOT NULL DEFAULT 0,
  closing_adj_mode VARCHAR(32) NOT NULL DEFAULT 'principal-interest',
  closing_adj_principal DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_target_balance DECIMAL(18, 2) NULL,
  closing_adj_principal_applied DECIMAL(18, 2) NOT NULL DEFAULT 0,
  closing_adj_interest_applied DECIMAL(18, 2) NOT NULL DEFAULT 0,
  monthly_schedule JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_loan_history (client_id, business_id, fy_id, loan_id),
  INDEX idx_loan_history_year (client_id, business_id, fy_start_year),
  INDEX idx_loan_history_loan (client_id, business_id, loan_id)
);

CREATE TABLE IF NOT EXISTS loan_schedule_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  loan_id VARCHAR(50) NOT NULL,
  loan_history_id VARCHAR(50) NOT NULL,
  serial_no INT NOT NULL DEFAULT 0,
  month INT NOT NULL DEFAULT 0,
  month_label VARCHAR(10) NOT NULL DEFAULT '',
  year INT NOT NULL DEFAULT 0,
  emi DECIMAL(18, 2) NOT NULL DEFAULT 0,
  principal DECIMAL(18, 2) NOT NULL DEFAULT 0,
  interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  is_prepayment TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  INDEX idx_loan_schedule_fs (client_id, fy_id, business_id),
  INDEX idx_loan_schedule_loan (client_id, business_id, fy_id, loan_id),
  INDEX idx_loan_schedule_history (loan_history_id)
);

CREATE TABLE IF NOT EXISTS loan_fy_summary (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  long_term_closing DECIMAL(18, 2) NOT NULL DEFAULT 0,
  short_term_closing DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_interest DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_principal_repaid DECIMAL(18, 2) NOT NULL DEFAULT 0,
  consolidated_cash_flow JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_loan_fy_summary (client_id, fy_id, business_id),
  INDEX idx_loan_fy_summary_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS note_sub_amount_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  note_key VARCHAR(60) NOT NULL,
  sub_id VARCHAR(120) NOT NULL,
  current_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  previous_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_note_sub_amount (client_id, fy_id, business_id, note_key, sub_id),
  INDEX idx_note_sub_amount_fs (client_id, fy_id, business_id),
  INDEX idx_note_sub_amount_note (client_id, fy_id, business_id, note_key)
);

CREATE TABLE IF NOT EXISTS note_line_rows (
  id VARCHAR(50) NOT NULL,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  line_kind VARCHAR(30) NOT NULL,
  note_key VARCHAR(60) NULL,
  reference_id VARCHAR(100) NOT NULL DEFAULT '',
  line_sign VARCHAR(10) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (client_id, fy_id, business_id, id),
  INDEX idx_note_line_rows_fs (client_id, fy_id, business_id),
  INDEX idx_note_line_rows_kind (client_id, fy_id, business_id, line_kind)
);

CREATE TABLE IF NOT EXISTS note_total_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  note_key VARCHAR(60) NOT NULL,
  current_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  previous_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_note_total (client_id, fy_id, business_id, note_key),
  INDEX idx_note_total_fs (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS note_cash_adjustment (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  current_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  previous_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_note_cash_adjustment (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS note_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_note_history (client_id, business_id, fy_id),
  INDEX idx_note_history_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS bs_statement_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  row_id VARCHAR(120) NULL,
  label VARCHAR(500) NOT NULL DEFAULT '',
  current_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  previous_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  note_no VARCHAR(20) NULL,
  note_key VARCHAR(60) NULL,
  note_sub_id VARCHAR(120) NULL,
  is_header TINYINT(1) NOT NULL DEFAULT 0,
  is_sub_header TINYINT(1) NOT NULL DEFAULT 0,
  is_total TINYINT(1) NOT NULL DEFAULT 0,
  is_grand_total TINYINT(1) NOT NULL DEFAULT 0,
  is_sub_line TINYINT(1) NOT NULL DEFAULT 0,
  indent INT NOT NULL DEFAULT 0,
  blank_amounts TINYINT(1) NOT NULL DEFAULT 0,
  is_spacer TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_bs_statement_row (client_id, fy_id, business_id, sort_order),
  INDEX idx_bs_statement_fs (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS pl_statement_rows (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  row_id VARCHAR(120) NULL,
  label VARCHAR(500) NOT NULL DEFAULT '',
  current_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  previous_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  note_no VARCHAR(20) NULL,
  note_key VARCHAR(60) NULL,
  note_sub_id VARCHAR(120) NULL,
  is_header TINYINT(1) NOT NULL DEFAULT 0,
  is_sub_header TINYINT(1) NOT NULL DEFAULT 0,
  is_total TINYINT(1) NOT NULL DEFAULT 0,
  is_grand_total TINYINT(1) NOT NULL DEFAULT 0,
  is_sub_line TINYINT(1) NOT NULL DEFAULT 0,
  indent INT NOT NULL DEFAULT 0,
  blank_amounts TINYINT(1) NOT NULL DEFAULT 0,
  is_spacer TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_pl_statement_row (client_id, fy_id, business_id, sort_order),
  INDEX idx_pl_statement_fs (client_id, fy_id, business_id)
);

CREATE TABLE IF NOT EXISTS statement_fy_summary (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  sources_total_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sources_total_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  application_total_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  application_total_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  net_profit_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  net_profit_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  gross_profit_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  gross_profit_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_income_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_income_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_expenses_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  total_expenses_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  cash_adjustment_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  cash_adjustment_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sources_application_diff_current DECIMAL(18, 2) NOT NULL DEFAULT 0,
  sources_application_diff_previous DECIMAL(18, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_statement_fy_summary (client_id, fy_id, business_id),
  INDEX idx_statement_fy_summary_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS statement_history (
  id VARCHAR(50) PRIMARY KEY,
  client_id VARCHAR(50) NOT NULL,
  business_id VARCHAR(50) NOT NULL,
  fy_id VARCHAR(50) NOT NULL,
  fy_label VARCHAR(20) NOT NULL DEFAULT '',
  fy_start_year INT NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(50) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id VARCHAR(50) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(255) NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY uniq_statement_history (client_id, business_id, fy_id),
  INDEX idx_statement_history_year (client_id, business_id, fy_start_year)
);

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  payload JSON NOT NULL
);
